name: IPV4 COLLECTOR

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Execute PHP script
        run: |
          php collect.php

      - name: Configure Git
        run: |
          git config --local user.email "vip.mahditaheri@gmail.com"
          git config --local user.name "MhdiTaheri"
          
      - name: Commit Changes
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "New IPV4 Added ✅ - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          
      - name: Pull Changes
        run: |
          git pull --rebase origin main || true  # Use '|| true' to continue execution even if there's an error
          
      - name: Push Changes
        run: |
          git push origin main
