name: "IPV4 COLLECTOR"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/65 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Execute PHP script
        run: |
          php collect.php
          git config --global user.email "mahdiritahe@gmail.com"
          git config --global user.name "MhdiTaheri-helper"
          git config credential.helper store
          git add -A
          git commit -m "New server Added ✅ - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git pull
          git push
